sudo: false
git:
  depth: 1
language: ruby
bundler_args: --without development production --deployment --jobs=4 --retry=5
cache: bundler

rvm:
  - jruby-9.2.11.1
jdk:
  - openjdk8
matrix:
  include:
    - { rvm: jruby-9.2.11.1 }

env:
  - JRUBY_OPTS="--dev -J-Xmx900m" DISPLAY=:99.0 LOGGER_LEVEL=WARN TRAVIS_NODE_VERSION="8"

before_install:
  - gem update --system 3.1.3
  - gem --version
  - gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
  - gem install bundler -v '2.1.4'

before_script:
  - ./script/front-end-build.sh

script:
  - ./script/front-end-tests.sh
  - RAILS_ENV=test bundle exec rspec
